### ISSUE TITLE
Changing the bibliographical information of published materials

### ISSUE THREAD

**Issue by NTNUbeta** [PoeticMediaLab/Lacuna#228]
How can an instructor change the bibliographical information of a published material? When choosing the material and edit, one can only make changes to "Content", "About" and "Syllabus". Where is the bibliographical section?

**Comment by dabush** [comment]
Thanks for drawing this to our attention. We need to update documentation to reflect this. Since the "Biblio" is technically a separate node from the published material, it has to be edited separately. The easiest way to do this is to go to **content** -> set type to **biblio** -> find the appropriate entry and edit.
